---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/authors":
    get:
      summary: list authors
      responses:
        '200':
          description: successful
    post:
      summary: create author
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/api/authors/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: show author
      responses:
        '200':
          description: successful
    put:
      summary: update author
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        '200':
          description: successful
    delete:
      summary: delete author
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
