# Config for Rubocop.

inherit_gem:
  rubocop-configs:
    - _all_cops.yml
    - _ruby.yml
    - bundler.yml
    - factory_bot.yml
    - performance.yml
    - rails.yml
    - rake.yml
    - rspec.yml
    - rspec_rails.yml
    - thread_safety.yml

AllCops:
  TargetRubyVersion: 3.3

Layout/RedundantLineBreak:
  Exclude:
    - 'factories/**/*.rb'

Naming/FileName:
  Exclude:
    - .tools/Gemfile

Rails/Output:
  Exclude:
    - db/seeds.rb

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/RepeatedExampleGroupBody:
  Exclude:
    - 'spec/requests/**/*.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - '.tools/**/*.rb'

Style/Documentation:
  Exclude:
    - 'app/serializers/**/*.rb'
    - 'config/**/*.rb'
    - 'db/migrate/*.rb'

Style/DocumentationMethod:
  Exclude:
    - 'config/**/*.rb'
    - 'db/migrate/*.rb'
  AllowedMethods:
    - object_params

Style/SingleLineDoEndBlock:
  Exclude:
    - 'spec/requests/**/*.rb'

Style/TopLevelMethodDefinition:
  Exclude:
    - db/seeds.rb

ThreadSafety/ClassAndModuleAttributes:
  Exclude:
    - 'app/controllers/**/*.rb'

# Lines taken from rswag-specs, .rubocop_rspec_alias_config.yml:
RSpec:
  Language:
    ExampleGroups:
      Regular:
        - path
        - response
        - get
        - post
        - patch
        - put
        - delete
        - head
        - options
        - trace
    Examples:
      Regular:
        - run_test!
