# Config for Rubocop.

inherit_gem:
  rubocop-configs:
    - _all_cops.yml
    - _ruby.yml
    - bundler.yml
    - factory_bot.yml
    - performance.yml
    - rails.yml
    - rake.yml
    - rspec.yml
    - rspec_rails.yml
    - rswag.yml
    - thread_safety.yml

AllCops:
  TargetRubyVersion: 3.3

Layout/RedundantLineBreak:
  Exclude:
    - 'factories/**/*.rb'

Naming/FileName:
  Exclude:
    - .tools/Gemfile

RSpec/ContextWording:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - '.tools/**/*.rb'

Style/Documentation:
  Exclude:
    - 'app/serializers/**/*.rb'

Style/DocumentationMethod:
  AllowedMethods:
    - object_params

ThreadSafety/ClassAndModuleAttributes:
  Exclude:
    - 'app/controllers/**/*.rb'
